### PR TITLE
test: configure `jest` to run TypeScript tests [POC]

### PR DESCRIPTION
**Pull request by tbouffard**
**THIS IS A POC which is a WIP**
covers #65

Use `jest` and `ts-jest`.

TODO
- [ ] configure jest to use ESM
- [ ] if jest config file has a cjs extension, update the the estlint npm scripts to consider this extension

### Current error

I am currently unable to configure jest (and ts-jest) to use ESM.
So, it uses CommonJS.

It produces an error while running
`Cannot find module 'bpmn-visualization' from 'src/plugins-support.ts'`

I tried the following but got got the same error:
-  add bpmn-visualization in dependencies and devDependencies, with or without bpmn-visualization in peerDependencies
- using a mapper as described in https://github.com/jestjs/jest/issues/2447#issuecomment-297766714
- The problem should be fixed by https://github.com/jestjs/jest/pull/9511

--> not the cause of the problem

While investigating, I found https://stackoverflow.com/a/68724825 which mention that the error could be due to a package with main property in package.json. This is the case for bpmn-visualization@0.38.0.
I check the stack trace and add logs to jest resolver.js (code at the end of the paragraph)

```
@@jest-resolver resolveModule: from /development/process-analytics/bv-experimental-add-ons/packages/addons/src/bpmn-elements.ts / moduleName bpmn-visualization
@@jest-resolver dirname: /development/process-analytics/bv-experimental-add-ons/packages/addons/src
@@jest-resolver - resolved module: null
```

I then manually updated the package.json file by adding a main property pointing to the ESM bundle to see if jest is resolving the bundle. The resolution succeeds, but as the bundle is not in the CommonJS format, the run fails.
```
@@jest-resolver resolveModule: from /development/process-analytics/bv-experimental-add-ons/packages/addons/src/bpmn-elements.ts / moduleName bpmn-visualization
@@jest-resolver dirname: /development/process-analytics/bv-experimental-add-ons/packages/addons/src
@@jest-resolver - resolved module: /development/process-analytics/bv-experimental-add-ons/node_modules/bpmn-visualization/dist/bpmn-visualization.esm.js
 FAIL  __tests__/plugins-support.test.ts
  ● Test suite failed to run
Test suite failed to run
    Jest encountered an unexpected token
    Jest failed to parse a file.
...
```

Using an older version of bpmn-visualization including a CommonJs works (this requires to comment some code that relies on newer API not available in this version). I make it work with version 0.27.0.

in node_modules/jest-resolve/build/resolver.js (jest v29.6.2) in the `resolveModule` function (line 348)
```js
    const dirname = path().dirname(from);
    console.info('@@jest-resolver dirname:', dirname)
    const module =
      this.resolveStubModuleName(from, moduleName) ||
      this.resolveModuleFromDirIfExists(dirname, moduleName, options);
    console.info('@@jest-resolver - resolved module:', module)
```

### Past errors

✔️ Side effects on other build fails. Fixed by 627d73d
* TS compilation errors in the `demo`
```
Error: src/overlays.ts(19,49): error TS2307: Cannot find module '@process-analytics/bv-experimental-add-ons' or its corresponding type declarations.
Error: src/path-resolver.ts(19,39): error TS2307: Cannot find module '@process-analytics/bv-experimental-add-ons' or its corresponding type declarations.
Error: src/path-resolver.ts(60,119): error TS7006: Parameter 'kind' implicitly has an 'any' type.
```
* TS compilation errors in `check-ts-support`
```
Error: src/index.ts(18,52): error TS2307: Cannot find module '@process-analytics/bv-experimental-add-ons' or its corresponding type declarations.
```

### CODE REVIEW

**Comment by tbouffard** [comment]
Superseded by #95
